-- MySQL Script generated by MySQL Workbench
-- Wed Oct 14 10:05:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `iva` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`request` (
  `id` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `details` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`feature` (
  `id` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `details` VARCHAR(45) NOT NULL,
  `Product_id` INT NOT NULL,
  `Request_idtable1` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Feature_Product1_idx` (`Product_id` ASC) VISIBLE,
  INDEX `fk_Feature_Request1_idx` (`Request_idtable1` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `contact` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `client_id` INT UNSIGNED NOT NULL,
  `manager_id1` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Rol_Client1_idx` (`client_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Rol_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Rol1_idx` (`Rol_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branch_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch_has_Product` (
  `branch_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`branch_id`, `product_id`),
  INDEX `fk_Branch_has_Product_Product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_Branch_has_Product_Branch1_idx` (`branch_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `product_id` INT NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  INDEX `fk_Status_Product1_idx` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_Request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_Request` (
  `user_id` INT NOT NULL,
  `request_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `request_id`),
  INDEX `fk_User_has_Request_Request1_idx` (`request_id` ASC) VISIBLE,
  INDEX `fk_User_has_Request_User1_idx` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
