-- MySQL Script generated by MySQL Workbench
-- Thu Oct 15 10:47:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `iva` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`request` (
  `id` INT NOT NULL,
  `date` DATE NOT NULL,
  `details` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`feature` (
  `id` INT NOT NULL,
  `date` DATE NOT NULL,
  `detail` VARCHAR(45) NOT NULL,
  `Product_id` INT NULL,
  `Request_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Feature_Product1_idx` (`Product_id` ASC) VISIBLE,
  INDEX `fk_Feature_Request1_idx` (`Request_id` ASC) VISIBLE,
  CONSTRAINT `fk_Feature_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Feature_Request1`
    FOREIGN KEY (`Request_id`)
    REFERENCES `mydb`.`request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `contact` CHAR(12) NOT NULL,
  `Rol_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Rol1_idx` (`Rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Rol1`
    FOREIGN KEY (`Rol_id`)
    REFERENCES `mydb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branch_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch_has_Product` (
  `id` INT(11) NULL,
  `branch_id` INT NULL,
  `product_id` INT NULL,
  INDEX `fk_Branch_has_Product_Product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_Branch_has_Product_Branch1_idx` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_Branch_has_Product_Branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Branch_has_Product_Product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `id` VARCHAR(45) NULL,
  `product_id` INT NULL,
  `Description` VARCHAR(45) NULL,
  INDEX `fk_Status_Product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Status_Product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_Request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_Request` (
  `id` INT(11) NULL,
  `user_id` INT(11) NULL,
  `request_id` INT(11) NULL,
  `user_has_Requestcol` VARCHAR(45) NULL,
  INDEX `fk_User_has_Request_Request1_idx` (`request_id` ASC) VISIBLE,
  INDEX `fk_User_has_Request_User1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Request_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Request_Request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `mydb`.`request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
